project:
  type: website
  preview:
      port: 3000
      browser: true

website:
  site-url: https://sinanpl.github.io/
  favicon: favicon.png
  navbar:
    left: 
      - text: home
        href: .
    right:
      - text: about
        file: about.qmd
      - icon: github
        href: https://github.com/sinanpl/sinanpl.github.io
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      - flatly
      - styles.scss

execute: 
  freeze: auto
